### ISSUE TITLE
This Demo can not get the email about  SimpleID-Verification 

### ISSUE THREAD

**Issue by syuukawa** [simplesecure/dev-app#1]
This Demo can not get the email about  SimpleID-Verification

**Comment by jehunter5811** [comment]
@syuukawa Are you saying you didn't get the verification email when signing up for a developer account?

**Comment by syuukawa** [comment]
Yes : 
I just got the SimpleID-Mnemonic <noreply@simpleid.xyz>; But no SimpleID-Verification 
In my localhost Env

**Comment by jehunter5811** [comment]
Ah, yes that's because the developer app is not available to be run locally. The code is available for audit, but you are not going to be able to connect to our database through a locally running version of the application. 

Please sign up for a developer account here: https://app.simpleid.xyz

Once you've done so, you can create a project and select modules. Then you'll have your apiKey and devId needed to build your own apps with SimpleID.

**Comment by syuukawa** [comment]
I thinks ,I have got that How to use the SimpleID; Thanks @jehunter5811

**Comment by jehunter5811** [comment]
You're welcome! If you'd like to join our slack, you can do so here: https://join.slack.com/t/simpleidxyz/shared_invite/enQtNzE1MTcxMDQzMzk1LWNlZGM4MDE1ODUzMWZkOGY4NTYzY2M3YjQ1MzUzYTJlM2YyMmM0NmZjNmQ3M2E1MGE0NGI5NjhkYmY2ZmI3YWY
